### ISSUE TITLE
Hit an exception when running against this that uses `toset`

### ISSUE THREAD

**Issue by sontek** [cloud-custodian/tfparse#35]
I hit this exception:

```
Traceback (most recent call last):
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-left-m2D9Q8mD-py3.10/bin/c7n-left", line 6, in <module>
    sys.exit(cli())
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-left-m2D9Q8mD-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-left-m2D9Q8mD-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-left-m2D9Q8mD-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-left-m2D9Q8mD-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-left-m2D9Q8mD-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/john/code/stacklet/cloud-custodian/tools/c7n_left/c7n_left/cli.py", line 41, in run
    runner.run()
  File "/Users/john/code/stacklet/cloud-custodian/tools/c7n_left/c7n_left/provider.py", line 61, in run
    for rtype, resources in graph.get_resources_by_type():
  File "/Users/john/code/stacklet/cloud-custodian/tools/c7n_left/c7n_left/provider.py", line 284, in get_resources_by_type
    resources.append(self.as_resource(name, data))
  File "/Users/john/code/stacklet/cloud-custodian/tools/c7n_left/c7n_left/provider.py", line 288, in as_resource
    if isinstance(data["__tfmeta"], list):
KeyError: '__tfmeta'
```

when running against this TF File:

```
locals {
  cluster_endpoints = toset(["us-east-1-eks-01", "us-east-1-eks-02"])
  pages_to_monitor  = toset([{ path = "/pricing", name = "pricing" }, { path = "/about/", name = "about" }])
  cluster_pages_monitor = distinct(flatten([
    for ep in local.cluster_endpoints : [
      for page in local.pages_to_monitor : {
        page    = page
        cluster = ep
      }
    ]
  ]))
}
# Healthcheck per cluster and page
resource "aws_route53_health_check" "cluster_pages" {
  for_each          = { for entry in local.cluster_pages_monitor : "${entry.cluster}.${entry.page.name}" => entry }
  fqdn              = "${each.value.cluster}.${var.domain}"
  port              = 443
  type              = "HTTPS"
  resource_path     = each.value.page.path
  failure_threshold = "2"
  request_interval  = "10"

  tags = {
    Name    = "${var.domain}-${each.value.cluster}-${each.value.page.name}"
    Cluster = each.value.cluster
  }
}

resource "aws_route53_health_check" "cluster_aggregate" {
  for_each               = local.cluster_endpoints
  type                   = "CALCULATED"
  child_health_threshold = length([for s in aws_route53_health_check.cluster_pages : s.id if s.tags_all["Cluster"] == each.key])
  child_healthchecks     = [for s in aws_route53_health_check.cluster_pages : s.id if s.tags_all["Cluster"] == each.key]

  tags = {
    Name    = "${var.domain}-${each.key}-agg"
    Cluster = each.key
  }
}
resource "aws_sns_topic" "failed_dns_healthchecks" {
  name = "${var.environment}-dns-healthcheck-failures"
}
resource "aws_sns_topic_subscription" "monitoring_pagerduty" {
  topic_arn              = aws_sns_topic.failed_dns_healthchecks.arn
  protocol               = "https"
  endpoint               = "https://events.pagerduty.com/integration/c0cac4d374f04806c0d7029726a7059e/enqueue"
  endpoint_auto_confirms = true
}
resource "aws_cloudwatch_metric_alarm" "cluster_agg_healthcheck_failed" {
  for_each            = local.cluster_endpoints
  alarm_name          = "${var.environment}_${each.key}_agg_healthcheck_failed"
  namespace           = "AWS/Route53"
  metric_name         = "HealthCheckStatus"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = "1"
  period              = "60"
  statistic           = "Minimum"
  threshold           = "1"
  unit                = "None"
  dimensions = {
    HealthCheckId = [for s in aws_route53_health_check.cluster_aggregate : s.id if s.tags_all["Cluster"] == each.key][0]
  }
  alarm_description  = "This metric monitors whether the cluster aggregate healthcheck is down or not."
  alarm_actions      = [aws_sns_topic.failed_dns_healthchecks.arn]
  ok_actions         = [aws_sns_topic.failed_dns_healthchecks.arn]
  treat_missing_data = "breaching"
  depends_on         = ["aws_route53_health_check.cluster_aggregate"]

  tags = {
    Cluster = each.key
  }
}
```

The data looked like this:

```
{'about"]': {'__tfmeta': {'filename': 'dns_healthchecks.tf',
                          'line_end': 27,
                          'line_start': 14},
             'failure_threshold': '2',
             'for_each': {'us-east-1-eks-01.about': {'cluster': 'us-east-1-eks-01',
                                                     'page': {'name': 'about',
                                                              'path': '/about/'}},
                          'us-east-1-eks-01.pricing': {'cluster': 'us-east-1-eks-01',
                                                       'page': {'name': 'pricing',
                                                                'path': '/pricing'}},
                          'us-east-1-eks-02.about': {'cluster': 'us-east-1-eks-02',
                                                     'page': {'name': 'about',
                                                              'path': '/about/'}},
                          'us-east-1-eks-02.pricing': {'cluster': 'us-east-1-eks-02',
                                                       'page': {'name': 'pricing',
                                                                'path': '/pricing'}}},
             'fqdn': 'us-east-1-eks-01.staging.com',
             'id': '98434e8a-1a52-4e94-a603-4e503168aab6',
             'port': 443,
             'request_interval': '10',
             'resource_path': '/about/',
             'tags': {'Cluster': 'us-east-1-eks-01',
                      'Name': 'staging.com-us-east-1-eks-01-about'},
             'type': 'HTTPS'},
 'pricing"]': {'__tfmeta': {'filename': 'dns_healthchecks.tf',
                            'line_end': 27,
                            'line_start': 14},
               'failure_threshold': '2',
               'for_each': {'us-east-1-eks-01.about': {'cluster': 'us-east-1-eks-01',
                                                       'page': {'name': 'about',
                                                                'path': '/about/'}},
                            'us-east-1-eks-01.pricing': {'cluster': 'us-east-1-eks-01',
                                                         'page': {'name': 'pricing',
                                                                  'path': '/pricing'}},
                            'us-east-1-eks-02.about': {'cluster': 'us-east-1-eks-02',
                                                       'page': {'name': 'about',
                                                                'path': '/about/'}},
                            'us-east-1-eks-02.pricing': {'cluster': 'us-east-1-eks-02',
                                                         'page': {'name': 'pricing',
                                                                  'path': '/pricing'}}},
               'fqdn': 'us-east-1-eks-01.staging.com',
               'id': 'f95f4895-f142-4942-a74a-0a1b2043fe8c',
               'port': 443,
               'request_interval': '10',
               'resource_path': '/pricing',
               'tags': {'Cluster': 'us-east-1-eks-01',
                        'Name': 'staging.com-us-east-1-eks-01-pricing'},
               'type': 'HTTPS'}}
```

**Comment by kapilt** [comment]
this should probably be filed against cloud custodian since its related c7n_left code versus tfparse itself generating an error.

**Comment by sontek** [comment]
@wwitzel3  It looks like you this issue with your latest collision changes?   I don't see a test in there that proves it but this seems to work now?

```
{
        "cluster": "us-east-1-eks-01",
        "page": {
                "name": "about",
                "path": "/about/"
        }
},
{
        "cluster": "us-east-1-eks-01",
        "page": {
                "name": "pricing",
                "path": "/pricing"
        }
},
```

**Comment by wwitzel3** [comment]
I wasn't sure if it would fix this and I didn't want to scope creep the fix by also trying to tackle this at the same time, but I thought it "might work". This issue is now here to capture adding a test to prevent regression.

**Comment by sontek** [comment]
This is still a problem with latest release:

```
❯ c7n-left run --policy-dir $HOME/code/sontek/k8s/policies/terraform/ -d $HOME/code/terraform-staging-new
DEBUG:c7n.iac:Loaded 562 resources
Running 1 policies
Traceback (most recent call last):
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/bin/c7n-left", line 6, in <module>
    sys.exit(cli())
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/cli.py", line 43, in run
    runner.run()
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/core.py", line 57, in run
    for rtype, resources in graph.get_resources_by_type():
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/providers/terraform/graph.py", line 34, in get_resources_by_type
    resources.append(self.as_resource(name, data))
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/providers/terraform/graph.py", line 38, in as_resource
    if isinstance(data["__tfmeta"], list):
KeyError: '__tfmeta'
```

The data still has the weird `about"]` keys in it:

```
{'about"]': {'__tfmeta': {'filename': 'dns_healthchecks.tf',
                          'line_end': 27,
                          'line_start': 14},
             'failure_threshold': '2',
             'for_each': {'us-east-1-eks-01.about': {'cluster': 'us-east-1-eks-01',
                                                     'page': {'name': 'about',
                                                              'path': '/about/'}},
                          'us-east-1-eks-01.pricing': {'cluster': 'us-east-1-eks-01',
                                                       'page': {'name': 'pricing',
                                                                'path': '/pricing'}},
                          'us-east-1-eks-02.about': {'cluster': 'us-east-1-eks-02',
                                                     'page': {'name': 'about',
                                                              'path': '/about/'}},
                          'us-east-1-eks-02.pricing': {'cluster': 'us-east-1-eks-02',
                                                       'page': {'name': 'pricing',
                                                                'path': '/pricing'}}},
             'fqdn': 'us-east-1-eks-01.staging.com',
             'id': '84d0d26f-2013-4d49-bc82-e65410935882',
             'port': 443,
             'request_interval': '10',
             'resource_path': '/about/',
             'tags': {'Cluster': 'us-east-1-eks-01',
                      'Name': 'staging.com-us-east-1-eks-01-about'},
             'type': 'HTTPS'},
 'pricing"]': {'__tfmeta': {'filename': 'dns_healthchecks.tf',
                            'line_end': 27,
                            'line_start': 14},
               'failure_threshold': '2',
               'for_each': {'us-east-1-eks-01.about': {'cluster': 'us-east-1-eks-01',
                                                       'page': {'name': 'about',
                                                                'path': '/about/'}},
                            'us-east-1-eks-01.pricing': {'cluster': 'us-east-1-eks-01',
                                                         'page': {'name': 'pricing',
                                                                  'path': '/pricing'}},
                            'us-east-1-eks-02.about': {'cluster': 'us-east-1-eks-02',
                                                       'page': {'name': 'about',
                                                                'path': '/about/'}},
                            'us-east-1-eks-02.pricing': {'cluster': 'us-east-1-eks-02',
                                                         'page': {'name': 'pricing',
                                                                  'path': '/pricing'}}},
               'fqdn': 'us-east-1-eks-01.staging.com',
               'id': 'b1d019c9-1bdb-4487-ae73-5e7807ec5a9c',
               'port': 443,
               'request_interval': '10',
               'resource_path': '/pricing',
               'tags': {'Cluster': 'us-east-1-eks-01',
                        'Name': 'staging.com-us-east-1-eks-01-pricing'},
               'type': 'HTTPS'}}
```

I think its still a bug on `tfparse` for now but after we fix this we can see if c7n-left has a problem as well

**Comment by sontek** [comment]
This was resolved in `main`!
