### ISSUE TITLE
Module file paths are incorrect

### ISSUE THREAD

**Issue by sontek** [cloud-custodian/tfparse#52]
If you write a policy against a resource that matches a module it comes up with a path:

```
terraform/staging-new/terraform-aws-modules/acm/aws/.terraform/modules/approval_staging_com_acm/main.tf
```

It should not have `terraform-aws-modules/acm/aws/` on there.   The file path should be:

```
terraform/staging-new/.terraform/modules/approval_staging_com_acm/main.tf
```

We'll need to pre-process it, so for example if they say:
```
source  = "terraform-aws-modules/notify-slack/aws"
```

thats just saying "pull from the terraform-aws-modules group in the registry" but on disk they don't include the group so we need to strip it.

This causes problems if you run `c7n-left` because its going to try to show you the source code but not be able to open the file:

```
Traceback (most recent call last):
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/bin/c7n-left", line 6, in <module>
    sys.exit(cli())
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/cli.py", line 43, in run
    runner.run()
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/core.py", line 63, in run
    self.reporter.on_results(result_set)
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/output.py", line 96, in on_results
    self.console.print(RichResult(r))
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/Users/john/Library/Caches/pypoetry/virtualenvs/c7n-nOD_wM_f-py3.10/lib/python3.10/site-packages/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/output.py", line 111, in __rich_console__
    lines = resource.get_source_lines()
  File "/Users/john/code/cloud-custodian/tools/c7n_left/c7n_left/providers/terraform/resource.py", line 38, in get_source_lines
    lines = (self.src_dir / self.filename).read_text().split("\n")
  File "/Users/john/.asdf/installs/python/3.10.5/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/Users/john/.asdf/installs/python/3.10.5/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/john/code/terraform/staging-new/terraform-aws-modules/acm/aws/.terraform/modules/approval_staging_com_acm/main.tf'
```

**Comment by sontek** [comment]
This happens if you run `terraform init` in the repo so it as a `modules.json` to read from.

**Comment by sontek** [comment]
This was resolved in `main`!
