### ISSUE TITLE
It is not handling `moved` resources 

### ISSUE THREAD

**Issue by sontek** [cloud-custodian/tfparse#53]
Example:

```
moved {
  from = aws_cloudwatch_log_group.task
  to   = aws_cloudwatch_log_group.task_upgrade_database
}
```

Error:

```
panic: unexpected resource type: moved

goroutine 17 [running, locked to thread]:
github.com/cloud-custodian/tfparse/gotfparse/pkg/converter.(*terraformConverter).visitBlock(0x105d74108?, 0x14000bc1500?, {0x0?, 0x0?}, 0x0?)
        /private/var/folders/0x/t100ywm11373bgv2zwxx7g7w0000gn/T/tmpt8qckrlx/src/github.com/cloud-custodian/tfparse/gotfparse/gotfparse/pkg/converter/converter.go:64 +0x288
github.com/cloud-custodian/tfparse/gotfparse/pkg/converter.(*terraformConverter).visitModule(0x11133ea20?, 0x14000d621e0, 0x0?)
        /private/var/folders/0x/t100ywm11373bgv2zwxx7g7w0000gn/T/tmpt8qckrlx/src/github.com/cloud-custodian/tfparse/gotfparse/gotfparse/pkg/converter/converter.go:45 +0x74
github.com/cloud-custodian/tfparse/gotfparse/pkg/converter.(*terraformConverter).VisitJSON(0x1400018f450)
        /private/var/folders/0x/t100ywm11373bgv2zwxx7g7w0000gn/T/tmpt8qckrlx/src/github.com/cloud-custodian/tfparse/gotfparse/gotfparse/pkg/converter/converter.go:34 +0xa4
main.Parse(0x14000190000?, 0x6000034043e8, 0x6000034042f8)
        /private/var/folders/0x/t100ywm11373bgv2zwxx7g7w0000gn/T/tmpt8qckrlx/src/github.com/cloud-custodian/tfparse/gotfparse/gotfparse/cmd/tfparse/main.go:35 +0x1b8
zsh: abort      c7n-left run --policy-dir $HOME/code/sontek/k8s/policies/terraform/ -d

```

**Comment by kapilt** [comment]
this seems specific to an extant pull request, ie this behavior wasn't on trunk last I looked, if it specific to the pull request, its best to leave as a comment on the pull request vs filing an issue.

**Comment by kapilt** [comment]
```
>>> import tfparse
>>> d = tfparse.load_from_path('.')
>>> d['moved']
{'__tfmeta': [{'filename': 'ecs.tf', 'line_start': 81, 'line_end': 84}, {'filename': 'ecs.tf', 'line_start': 61, 'line_end': 64}, {'filename': 'ecs.tf', 'line_start': 56, 'line_end': 59}, {'filename': 'ecs.tf', 'line_start': 51, 'line_end': 54}, {'filename': 'ecs.tf', 'line_start': 86, 'line_end': 89}], 'from': [None, None, None, None, None], 'id': ['4c480bea-cbe0-4e6e-b738-f947c0e499c8', '56740b85-3db3-4d2a-b135-1551483b104a', '566f2ed9-24c0-4cc8-ad9e-ab3abef4b24e', '622899e8-53f1-4e8a-9692-0e6284d96115', '69f7ec3a-4bb3-4482-bf21-0de8fce25fb3'], 'to': [None, None, None, None, None]}
```
